# Generated by Django 5.2.1 on 2025-07-10 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trackingNumber', models.CharField(max_length=15, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('currentStatus', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'db_table': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
            },
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='guide',
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedBy', models.CharField(max_length=20)),
                ('guide', models.ForeignKey(db_column='guideId', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipments.guia')),
            ],
            options={
                'verbose_name': 'Historial de Estatus',
                'verbose_name_plural': 'Historiales de Estatus',
                'db_table': 'StatusHistory',
            },
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
