# Generated by Django 5.2.1 on 2025-07-10 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_guia_usuario_remove_statuschange_guide_statushistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='guia',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guia',
            name='trackingNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='guia',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='guia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedBy', models.CharField(max_length=20)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatuses', to='shipments.guia')),
            ],
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
