# Generated by Django 5.2.1 on 2025-07-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_guia_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatus',
            options={'verbose_name': 'Estatus', 'verbose_name_plural': 'Estatus'},
        ),
        migrations.AlterField(
            model_name='estatus',
            name='guia',
            field=models.ForeignKey(db_column='guideId', on_delete=django.db.models.deletion.CASCADE, related_name='estatuses', to='shipments.guia'),
        ),
        migrations.AlterModelTable(
            name='estatus',
            table='StatusHistory',
        ),
    ]
