# Generated by Django 5.2.1 on 2025-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_estatus_options_alter_estatus_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='recipient',
            field=models.CharField(default='', max_length=100),
        ),
    ]
