# Generated by Django 5.2.1 on 2025-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_guia_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
